version: "3.7"

x-application: &application
  image: welsh-petitions/ruby
  build: docker/ruby
  environment:
    - DATABASE_URL=postgres://postgres:fUG1DnZpy1rNkxiO@postgres:5432
    - MEMCACHE_SERVERS=memcached:11211
    - SPROCKETS_CACHE=/cache
  volumes:
    - .:/app
    - bundle:/bundle
    - cache:/cache
  depends_on:
    - postgres
    - memcached

services:
  postgres:
    image: welsh-petitions/postgis
    build: docker/postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fUG1DnZpy1rNkxiO
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  memcached:
    image: memcached:1.5
    ports:
      - "11211:11211"

  web:
    <<: *application
    command: [
      "rails", "server",
      "-b", "0.0.0.0",
      "-p", "3000"
    ]
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  worker:
    <<: *application
    command: [
      "bin/delayed_job", "start",
      "-p", "worker",
      "--min-priority", "10",
      "--daemon_options", "-t"
    ]

  counter:
    <<: *application
    command: [
      "bin/delayed_job", "start",
      "-p", "counter",
      "--max-priority", "5",
      "--daemon_options", "-t"
    ]

volumes:
  bundle:
  db:
  cache:
