x-application: &application
  image: welsh-petitions/ruby
  build: docker/ruby
  volumes:
    - .:/app
    - bundle:/bundle
    - cache:/cache
  tmpfs:
    - /tmp/pids/
  depends_on:
    - postgres

x-environment: &environment
  DATABASE_URL: "postgres://postgres:fUG1DnZpy1rNkxiO@postgres:5432"
  DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: "true"
  SPROCKETS_CACHE: "/cache"
  PIDFILE: "/tmp/pids/server.pid"

services:
  postgres:
    image: welsh-petitions/postgis
    build: docker/postgis
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=fUG1DnZpy1rNkxiO
      - POSTGRES_DB=postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  web:
    <<: *application
    environment:
      <<: *environment
    command: [
      "rails", "server",
      "-b", "0.0.0.0",
      "-p", "3000"
    ]
    ports:
      - "127.0.0.1:3000:3000"
    stdin_open: true
    tty: true

  worker:
    <<: *application
    environment:
      <<: *environment
      MIN_PRIORITY: "10"
    command: [ "rake", "jobs:work" ]

  counter:
    <<: *application
    environment:
      <<: *environment
      MAX_PRIORITY: "5"
    command: [ "rake", "jobs:work" ]

volumes:
  bundle:
  db:
  cache:
