default: &default
  encoding: utf8
  url: <%= ENV.fetch("DATABASE_URL").sub("postgres://", "postgis://") %>
  pool: 5

development:
  <<: *default
  database: wpets_development

test:
  <<: *default
  database: wpets_test

production:
  <<: *default
  database: wpets_production
  pool: <%= ENV.fetch('WEB_CONCURRENCY_MAX_THREADS') { 32 }.to_i %>
