class ConvertIntegerIdsToBigInt < ActiveRecord::Migration[5.2]
  def up
    change_column :admin_users, :id, :bigint
    change_column :constituency_petition_journals, :id, :bigint
    change_column :constituency_petition_journals, :petition_id, :bigint
    change_column :contacts, :id, :bigint
    change_column :contacts, :signature_id, :bigint
    change_column :country_petition_journals, :id, :bigint
    change_column :country_petition_journals, :petition_id, :bigint
    change_column :debate_outcomes, :id, :bigint
    change_column :debate_outcomes, :petition_id, :bigint
    change_column :delayed_jobs, :id, :bigint
    change_column :domains, :id, :bigint
    change_column :domains, :canonical_domain_id, :bigint
    change_column :email_requested_receipts, :id, :bigint
    change_column :email_requested_receipts, :petition_id, :bigint
    change_column :feedback, :id, :bigint
    change_column :holidays, :id, :bigint
    change_column :invalidations, :id, :bigint
    change_column :invalidations, :petition_id, :bigint
    change_column :languages, :id, :bigint
    change_column :members, :id, :bigint
    change_column :notes, :id, :bigint
    change_column :notes, :petition_id, :bigint
    change_column :petition_emails, :id, :bigint
    change_column :petition_emails, :petition_id, :bigint
    change_column :petition_statistics, :id, :bigint
    change_column :petition_statistics, :petition_id, :bigint
    change_column :petitions, :id, :bigint
    change_column :petitions, :locked_by_id, :bigint
    change_column :rate_limits, :id, :bigint
    change_column :rejection_reasons, :id, :bigint
    change_column :rejections, :id, :bigint
    change_column :rejections, :petition_id, :bigint
    change_column :signatures, :id, :bigint
    change_column :signatures, :petition_id, :bigint
    change_column :signatures, :invalidation_id, :bigint
    change_column :sites, :id, :bigint
    change_column :tags, :id, :bigint
    change_column :tasks, :id, :bigint
    change_column :topics, :id, :bigint
    change_column :trending_domains, :id, :bigint
    change_column :trending_domains, :petition_id, :bigint
    change_column :trending_ips, :id, :bigint
    change_column :trending_ips, :petition_id, :bigint
  end

  def down
    change_column :admin_users, :id, :integer
    change_column :constituency_petition_journals, :id, :integer
    change_column :constituency_petition_journals, :petition_id, :integer
    change_column :contacts, :id, :integer
    change_column :contacts, :signature_id, :integer
    change_column :country_petition_journals, :id, :integer
    change_column :country_petition_journals, :petition_id, :integer
    change_column :debate_outcomes, :id, :integer
    change_column :debate_outcomes, :petition_id, :integer
    change_column :delayed_jobs, :id, :integer
    change_column :domains, :id, :integer
    change_column :domains, :canonical_domain_id, :integer
    change_column :email_requested_receipts, :id, :integer
    change_column :email_requested_receipts, :petition_id, :integer
    change_column :feedback, :id, :integer
    change_column :holidays, :id, :integer
    change_column :invalidations, :id, :integer
    change_column :invalidations, :petition_id, :integer
    change_column :languages, :id, :integer
    change_column :members, :id, :integer
    change_column :notes, :id, :integer
    change_column :notes, :petition_id, :integer
    change_column :petition_emails, :id, :integer
    change_column :petition_emails, :petition_id, :integer
    change_column :petition_statistics, :id, :integer
    change_column :petition_statistics, :petition_id, :integer
    change_column :petitions, :id, :integer
    change_column :petitions, :locked_by_id, :integer
    change_column :rate_limits, :id, :integer
    change_column :rejection_reasons, :id, :integer
    change_column :rejections, :id, :integer
    change_column :rejections, :petition_id, :integer
    change_column :signatures, :id, :integer
    change_column :signatures, :petition_id, :integer
    change_column :signatures, :invalidation_id, :integer
    change_column :sites, :id, :integer
    change_column :tags, :id, :integer
    change_column :tasks, :id, :integer
    change_column :topics, :id, :integer
    change_column :trending_domains, :id, :integer
    change_column :trending_domains, :petition_id, :integer
    change_column :trending_ips, :id, :integer
    change_column :trending_ips, :petition_id, :integer
  end
end
